nelmio_api_doc:
    documentation:
        info:
            title: Task Followup
            description: Task followup web application is a RESTful APIs for managing tasks.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
